extends: '@absolunet/core'

env:
  node: true
  browser: true

globals:
  angular: true

rules:
  class-methods-use-this: [off]
  no-restricted-globals: [off]
  consistent-this: [error, self, _self, vm]
